id = "make"
name = "Make"
description = "Makefile syntax highlighting"
version = "1.1.1"
schema_version = 1
authors = [
  "Caius Durling <dev@caius.name>",
  "d1y <chenhonzhou@gmail.com>",
  "Marshall Bowers <elliott.codes@gmail.com>",
  "Luke Naylor <luke@grahamnaylor.net>",
  "Igor Támara <igor.tamara@gmail.com>",
  "Michael Alexander <michael.alexander@karlstorz.com>",
]
repository = "https://github.com/caius/zed-make"

[grammars.make]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-make"
commit = "5e9e8f8ff3387b0edcaa90f46ddf3629f4cfeb1d"
